# Generated by Django 4.2.5 on 2023-12-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_studentinfomodel_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfomodel',
            name='roll',
            field=models.IntegerField(null=True),
        ),
    ]
