# Generated by Django 4.2 on 2023-12-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='accoutn_type',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='brith_date',
            new_name='birth_date',
        ),
    ]
