# Generated by Django 4.2.5 on 2023-12-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_studentinfomodel_teacherinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='section',
            field=models.CharField(max_length=70),
        ),
    ]
