# Generated by Django 4.2.5 on 2023-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_employeemodel_managermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=10)),
                ('attendence', models.BooleanField()),
                ('home_work', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MeModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('first_app.friendmodel',),
        ),
    ]
