# Generated by Django 4.2 on 2023-12-25 05:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='users/avatar.jpg', upload_to=accounts.models.user_directory_path),
        ),
    ]
